# Generated by Django 2.2.13 on 2020-07-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_ID', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('Course_Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('Letter_Grade', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('Numerical_Weightage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Student_Year', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UVACS_Tables.Course')),
                ('Student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UVACS_Tables.Student')),
                ('Transcript_Grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UVACS_Tables.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PreReq', to='UVACS_Tables.Course')),
                ('Desired_Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main', to='UVACS_Tables.Course')),
            ],
        ),
    ]
