# Generated by Django 2.2.2 on 2020-05-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_ID', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('Course_Name', models.CharField(max_length=100, null=True)),
                ('Course_PreRequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Profiles.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('Letter_Grade', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('Numerical_Weightage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Student_Year', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Profiles.Course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Profiles.Student')),
                ('Transcript_Grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Profiles.Grade')),
            ],
        ),
    ]
