# Generated by Django 2.2.2 on 2020-05-26 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_remove_course_course_prerequisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='PreReq', to='Profiles.Course')),
                ('Desired_Course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='Profiles.Course')),
            ],
        ),
    ]
