# Generated by Django 2.2.2 on 2020-05-27 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='Course_Prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PreReq', to='Profiles.Course'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='Desired_Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main', to='Profiles.Course'),
        ),
    ]
