# Generated by Django 2.2.2 on 2020-05-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_auto_20200527_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Profiles.Course'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='Student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Profiles.Student'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='Transcript_Grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Profiles.Grade'),
        ),
    ]
