# Generated by Django 2.2.2 on 2020-05-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_auto_20200527_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='Course_Prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PreReq', to='Profiles.Course'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='Desired_Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main', to='Profiles.Course'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='Course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profiles.Course'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='Student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profiles.Student'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='Transcript_Grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profiles.Grade'),
        ),
    ]
