# Generated by Django 2.2.2 on 2020-06-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profiles', '0006_auto_20200527_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignificantCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profiles.Grade')),
                ('Original_Course', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original', to='Profiles.Course')),
                ('SigCourse', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated', to='Profiles.Course')),
            ],
        ),
    ]
